backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

logo_url: https://verycool.tech/static/img/verycool_log.png

collections:
  - name: 'articles'
    label: 'Articles'
    folder: 'src/pages/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'template',
          widget: 'hidden',
          default: 'article',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Cover image',
          name: 'cover_image',
          widget: 'image',
          required: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Author', name: 'author', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'template',
              widget: 'hidden',
              default: 'page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
